name: Auto Request Reviewers by Target Branch (safe)

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    # SECURITY: do NOT checkout PR code here (we only use the event).
    steps:
      - name: Debug print event info
        run: |
          echo "PR base branch: ${{ github.event.pull_request.base.ref }}"
          echo "PR head branch: ${{ github.event.pull_request.head.ref }}"
          echo "PR author: ${{ github.event.pull_request.user.login }}"

      - name: Assign reviewers for develop
        if: ${{ github.event.pull_request.base.ref == 'develop' }}
        uses: peter-evans/request-review@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: 'PriyaGajjala,SreeDevopsNihi'

      - name: Assign reviewers for master
        if: ${{ github.event.pull_request.base.ref == 'master' }}
        uses: peter-evans/request-review@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: 'SreeDevopsNihi,vinodmk23j'

      - name: No automatic reviewers (other branches)
        if: ${{ github.event.pull_request.base.ref != 'develop' && github.event.pull_request.base.ref != 'master' }}
        run: echo "No auto-reviewers configured for branch '${{ github.event.pull_request.base.ref }}'"
